- Loop through dates since Jan 1 1950 to Dec 31 2018

- If the file for a day exists...
    - For states...
        - Groupby sims and states
        - Sum pop, hospital, power plant, mobile home
        - Get 10%, median, and 90% of each and place into a list [10,med,90] for that day
        - Add these values element-wise to the current total
        - For all states that don't have an entry, add [0,0,0] for the day
        - Calculate the mean of 10,med,90 for each day by dividing by the number of years (68 years for all days except Feb 29... divide by 17)
        - Then run a 7-day window average on each day for each state
    - For cwas...
        - Should be the same as above, but double check

In [ ]:
# Data list example
[{
    'State': 'AL',
    'Data': {
        '1':[10,med,90],
        '2':[10,med,90],
        ...,
        '366':[10,med,90]
    },
    ...,
    'State': 'WY',
    'Data': {
        '1':[10,med,90],
        '2':[10,med,90],
        ...,
        '366':[10,med,90]
    }
}]

In [25]:
from datetime import timedelta, date
import glob

In [15]:
def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)

In [42]:
start_date = date(1969, 1, 1)
end_date = date(1969, 1, 30)
for single_date in daterange(start_date, end_date):
    file_suff = single_date.strftime("%Y%m%d1630_pp")
    print(file_suff)
    print(glob.glob(f'/Volumes/Backup Plus/pas_output/simulationFiles/{file_suff}*'))

196901011630_pp
[]
196901021630_pp
[]
196901031630_pp
[]
196901041630_pp
[]
196901051630_pp
[]
196901061630_pp
[]
196901071630_pp
[]
196901081630_pp
[]
196901091630_pp
[]
196901101630_pp
[]
196901111630_pp
[]
196901121630_pp
[]
196901131630_pp
[]
196901141630_pp
[]
196901151630_pp
[]
196901161630_pp
[]
196901171630_pp
[]
196901181630_pp
[]
196901191630_pp
[]
196901201630_pp
[]
196901211630_pp
[]
196901221630_pp
['/Volumes/Backup Plus/pas_output/simulationFiles/196901221630_pp.psv.gz']
196901231630_pp
['/Volumes/Backup Plus/pas_output/simulationFiles/196901231630_pp.psv.gz']
196901241630_pp
[]
196901251630_pp
[]
196901261630_pp
[]
196901271630_pp
[]
196901281630_pp
[]
196901291630_pp
[]

In [23]:
df=pd.read_csv(glob.glob('/Volumes/Backup Plus/pas_output/simulationFiles/*')[0],sep='|')

In [45]:
start_date = date(1969, 1, 1)
end_date = date(1969, 1, 25)
for single_date in daterange(start_date, end_date):
    file_suff = single_date.strftime("%Y%m%d1630_pp")
    
    file = f'/Volumes/Backup Plus/pas_output/simulationFiles/{file_suff}.psv.gz'
    #print(file_suff)
    if (glob.glob(file)):
        
        df = pd.read_csv(file, sep="|")
        wfoDf = df.assign(category=df['wfos'].str.split(',')).explode('category').reset_index(drop=True)
        wfoDf.groupby(['category','sim']).sum().groupby('category').mean()
        
    else:
        
        # Need to add 0s
        pass
    #print(glob.glob(f'/Volumes/Backup Plus/pas_output/simulationFiles/{file_suff}*'))

KeyError: 'category'

In [44]:
wfoDf.groupby(['category','sim']).sum()

               population  distance  rating  hospitals  hospitalbeds  \
category sim
ILX      2           4384    2.5778       2          0             0
         4             80    1.9834       0          0             0
         5            128    4.0870       3          0             0
         6             96    1.4675       2          0             0
         7           1120    1.5525       2          0             0
...                   ...       ...     ...        ...           ...
LSX      1480       80272   17.2629       5          0             0
         1481         880    1.4745       3          0             0
         1482       35008    3.7658       1          0             0
         1483        1776    1.3402       0          1            75
         1484        7760    0.7956       1          0             0

               mobileparks  mobilehomes  psubstations  plines      slon  \
category sim
ILX      2               0            0             0       0 -268.5499
         4               0            0             0       0  -89.1560
         5               0            0             0       0  -89.2052
         6               0            0             0       0  -89.3346
         7               0            0             0       0  -89.2652
...                    ...          ...           ...     ...       ...
LSX      1480            3          225             2       4 -719.3715
         1481            0            0             0       0 -179.9330
         1482            0            0             4      10 -179.5790
         1483            0            0             0       0 -179.9650
         1484            0            0             0       0  -89.9613

                   slat      elon      elat
category sim
ILX      2     118.4842 -268.5219  118.5142
         4      39.2815  -89.1242   39.2963
         5      39.4475  -89.1443   39.4834
         6      39.3990  -89.3142   39.4132
         7      39.3255  -89.2403   39.3371
...                 ...       ...       ...
LSX      1480  311.6864 -719.1452  311.8542
         1481   77.8419 -179.9241   77.8615
         1482   77.5227 -179.5185   77.5494
         1483   77.6838 -179.9414   77.6900
         1484   38.6571  -89.9529   38.6666

[1835 rows x 13 columns]

In [46]:
df

Empty DataFrame
Columns: [sim, population, distance, rating, states, counties, wfos, hospitals, hospitalbeds, mobileparks, mobilehomes, psubstations, plines, slon, slat, elon, elat]
Index: []

## Checking for bad years

In [60]:
for file in glob.glob('/Volumes/Backup Plus/pas_output/simulationFiles/*')[0:2]:
    print(file)
    print(file.split('/')[-1][0:4])

/Volumes/Backup Plus/pas_output/simulationFiles/195001031630_pp.psv.gz
1950
/Volumes/Backup Plus/pas_output/simulationFiles/195001121630_pp.psv.gz
1950

In [68]:
df = pd.read_csv('/Volumes/Backup Plus/pas_output/simulationFiles/195001121630_pp.psv.gz',sep='|')

In [71]:
rando = []
rando.append(df['sim'].max())
rando

[nan]

In [66]:
yearDict = {}
for i in range(1950,2019):
    yearDict[str(i)] = []

In [72]:
for file in glob.glob('/Volumes/Backup Plus/pas_output/simulationFiles/*'):
    year = file.split('/')[-1][0:4]
    df = pd.read_csv(file, sep='|')
    maxSim = df['sim'].max()
    
    yearDict[year].append(maxSim)

/Users/josephpicca/anaconda/envs/impacts/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [75]:
yearDict['1950']

[1484,
 nan,
 nan,
 nan,
 2444,
 5223,
 9999,
 nan,
 6100,
 nan,
 nan,
 9996,
 nan,
 10000,
 754,
 nan,
 9998,
 603,
 3879,
 nan,
 4090,
 10000,
 nan,
 9988,
 10000,
 10000,
 nan,
 nan,
 nan,
 nan,
 10000,
 10000,
 17,
 9991,
 10000,
 10000,
 9994,
 nan,
 nan,
 9999,
 nan,
 9999,
 9991,
 nan,
 nan,
 nan,
 9999,
 10000,
 9998,
 4415,
 nan,
 nan,
 9994,
 1858,
 9998,
 10000,
 nan,
 nan,
 9979,
 9998,
 2417,
 10000,
 10000,
 10000,
 9998,
 10000,
 nan,
 340,
 9995,
 10000,
 9998,
 nan,
 9998,
 9999,
 10000,
 nan,
 10000,
 9999,
 nan,
 nan,
 nan,
 1491]